### ISSUE TITLE
QuickCollection (and possibly other constructors) break Backbone prototype chain

### ISSUE THREAD

**Issue by jtorodashcondev** [pwagener/backbone.conduit#53] opened 2015-11-18 16:27 UTC
Note the following code sample:

```javascript
var c = new Backbone.Conduit.QuickCollection;
c instanceof Backbone.Collection; // false
```

I believe this is due to the prototype established on line 28 of QuickCollection.js.

**Comment by pwagener** [comment] 2015-11-18 16:50
Note the easiest work-around here is to use the `Backbone.Conduit.haul.mixin(...)` instead of extends `Backbone.Conduit.QuickCollection` directly.  See here:

http://conduit.wagener.org/docs/QuickCollection/extendormixin.html

**Comment by pwagener** [comment] 2015-12-05 18:59
This is unfortunately the intended behavior.  The `Backbone.Collection` constructor does some unfortunate things performance-wise when you provide models.  I.e. this will not perform well:

```javascript
var myData = [ {}, {}, {}, ...]; // Assume it is 500K items
var myCollection = new Backbone.Collection(myData);
```

See [the annotated source code](http://backbonejs.org/docs/backbone.html#section-98) for what it does.  The calling of `this.reset(models, ...)` is what we avoid by breaking the inheritance chain.

I'm open for changing the behavior to work the other way, but I think the work-around behavior (i.e. using `Backbone.Conduit.haul.mixin(...)`) is reasonable if you really need to consider your collection an instance of `Backbone.Collection`.  Any feedback on this tradeoff would be welcome!

Closing this, as it works as designed.

**Closed by pwagener** 2015-12-05 18:59 UTC
